### ISSUE TITLE
Unable to Resolve Dependency: Could not resolve project :opencv

### ISSUE THREAD

**Issue by spatil063** [VlSomers/native-opencv-android-template#3]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :opencv.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :opencv.
Show Details
Affected Modules: app

**Comment by VlSomers** [comment]
Make sur you set the correct path to your _OpenCV-android-sdk_ in _gradle.properties_. For example, if the unzipped _OpenCV-android-sdk_ folder you just downloaded is located under _/Users/Example/Downloads/OpenCV-android-sdk_, use `opencvsdk=/Users/Example/Downloads/OpenCV-android-sdk`

**Comment by spatil063** [comment]
Everything is proper I had put opencvsdk=/Users/user/Downloads/OpenCV-android-sdk as the path in my  gradle.properties File

**Comment by VlSomers** [comment]
Which version of the OpenCV Android SDK did you downloaded?

**Comment by spatil063** [comment]
4.1.1

**Comment by VlSomers** [comment]
Ok, I'll come back to you later with an alternative solution to import OpenCV module

**Comment by melvincabatuan** [comment]
The template worked smoothly, I've just tested it recently [here.](https://github.com/melvincabatuan/HelloOpenCVAndroid)

**Comment by VlSomers** [comment]
@spatil063 Did you finally manage to make it work?

**Comment by VlSomers** [comment]
Closing the issue

**Comment by julian59189** [comment]
Hi, I am having the same problem. Downloaded `opencv-4.5.0-android-sdk.zip` from the link in the readme
Set the path properly:
`opencvsdk='~/Downloads/OpenCV-android-sdk45'`
`ls ~/Downloads/OpenCV-android-sdk45
LICENSE		README.android	samples		sdk`
`ls ~/Downloads/OpenCV-android-sdk45/sdk
build		build.gradle	etc		java		libcxx_helper	native`

Am I missing any files in my sdk?

**Comment by julian59189** [comment]
The mistake I made was the quotes around the sdk path. Changing that to:
`opencvsdk=~/Downloads/OpenCV-android-sdk45`
solved the problem. Just in case anybody is facing the same problem

**Comment by VlSomers** [comment]
> The mistake I made was the quotes around the sdk path. Changing that to:
> `opencvsdk=~/Downloads/OpenCV-android-sdk45`
> solved the problem. Just in case anybody is facing the same problem

Thanks for pointing this out!
