### ISSUE TITLE
Enable SURF

### ISSUE THREAD

**Issue by pro2on** [VlSomers/native-opencv-android-template#4]
Could you please clarify how to build openCV with contrib modules and enable SURF/SIRF and other non-free modules. As I understand they are disabled by default, so it's needed special CMAKE option OPENCV_ENABLE_NONFREE.

And thank you for this tutorial!

**Comment by VlSomers** [comment]
Sorry for the late reply, I don't know how to build OpenCV with contrib modules and enable non free modules. If you manage to make it work, do not hesitate to open a pull request on this repository.

**Comment by quickgrid** [comment]
This link provides prebuilt contrib version, https://pullrequest.opencv.org/buildbot/export/opencv_releases/master-contrib_pack-contrib-android/. I am using your template with `opencv contrib 4.2.0 and 4.3.0` in android without any error by just replacing opencv with opencv contrib from the link above.

**Comment by VlSomers** [comment]
> This link provides prebuilt contrib version, https://pullrequest.opencv.org/buildbot/export/opencv_releases/master-contrib_pack-contrib-android/. I am using your template with `opencv contrib 4.2.0 and 4.3.0` in android without any error by just replacing opencv with opencv contrib from the link above.

Thanks for sharing this solution! I'll probably add this to the Readme instructions in the future. Do not hesitate to open a pull request with instructions for your solution in the Readme if you want to contribute to the repository!
