### ISSUE TITLE
Can't use OpenCV's core / imgcodecs

### ISSUE THREAD

**Issue by muchorange** [VlSomers/native-opencv-android-template#5]
Hi @VlSomers,
Great tutorial! thanks for uploading it :)

I followed the tutorial, with the exception of the Camera, which I don't use in my Android app.
I'm using the same gradle version you used and same OpenCV version, on Ubuntu 16.04 Linux / Galaxy S10.

I have a fairly simple `native-lib.cpp` file:
```
#include <jni.h>
#include <string>
#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>

extern "C" JNIEXPORT jstring JNICALL
Java_com_ocv_MainActivity_ocvLoadImage(
        JNIEnv *env,
        jobject thiz) {
    using namespace cv;
    using namespace std;
    Mat image;
    string imageName = "/Pictures/images/image-001.jpg";
    image = imread(imageName, IMREAD_COLOR);
    std::string returnString = "OpenCV load image: ";
    if (! image.empty()){
        returnString.append(imageName);
    }
    return env -> NewStringUTF(returnString.c_str());
}
```

but when I run it I get the following errors:
```
undefined reference to cv::imread
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
Removing the call to `imread` works OK.

Think you can help?

**Comment by VlSomers** [comment]
Hello @orangesomethingorange,
Unfortunately I cannot help you for the moment as I don't have access to an Android environment already setup to quickly test your issue. I hope you'll find some help on your [other issue](https://github.com/opencv/opencv/issues/17519). 
Let me know if you find a solution, I might give it a try later if you don't find anything! :-)

**Comment by muchorange** [comment]
Hey @VlSomers 

thanks for the quick reply :)
I'll sure try and figure that out... thanks!
