### ISSUE TITLE
Reducing app size when not used

### ISSUE THREAD

**Issue by EmmanuelMess** [VlSomers/native-opencv-android-template#6]
If I add opencv to my project but don't use it, it adds 50MB of size to my app. Is there a way to remove unused functions in C++?

**Comment by VlSomers** [comment]
Sorry but I don't know how to do this. There's probably some ways to reduce apk size, but you'll have to search the web for more answers :-) If you find a solution, can you post the link here? Thank you and good luck for solving this!

**Comment by EmmanuelMess** [comment]
You can use the static libs instead (from the sdk) and configure a few things, I will upload a project to GitHub and add a link.

**Comment by EmmanuelMess** [comment]
Link: https://github.com/EmmanuelMess/Reduced-OpenCV-Android

**Comment by EmmanuelMess** [comment]
I am stuck, having these two issues: [Build statically, missing cv::countNonZero(cv::_InputArray const&)](https://answers.opencv.org/question/236576/build-statically-missing-cvcountnonzerocv_inputarray-const/) and [Building OpenCV statically in app fails “error: undefined reference to 'ippicvsRound_64f'”](https://stackoverflow.com/q/64361730/3124150). The time for this project has ended, but will update if some answers come back.

**Comment by VlSomers** [comment]
Sorry for these issues, I hope you're going to find some answers!

**Comment by ninh-huynh** [comment]
I've found these instruction located in *OpenCV-android-sdk/sdk/native/jni/OpenCVConfig.cmake*. 

```cmake
# ===================================================================================
#  The OpenCV CMake configuration file
#
#             ** File generated automatically, do not modify **
#
#  Usage from an external project:
#    In your CMakeLists.txt, add these lines:
#
#    find_package(OpenCV REQUIRED)
#    include_directories(${OpenCV_INCLUDE_DIRS}) # Not needed for CMake >= 2.8.11
#    target_link_libraries(MY_TARGET_NAME ${OpenCV_LIBS})
#
#    Or you can search for specific OpenCV modules:
#
#    find_package(OpenCV REQUIRED core videoio)
#
#    If the module is found then OPENCV_<MODULE>_FOUND is set to TRUE.
#
#    This file will define the following variables:
#      - OpenCV_LIBS                     : The list of all imported targets for OpenCV modules.
#      - OpenCV_INCLUDE_DIRS             : The OpenCV include directories.
#      - OpenCV_ANDROID_NATIVE_API_LEVEL : Minimum required level of Android API.
#      - OpenCV_VERSION                  : The version of this OpenCV build: "4.5.0"
#      - OpenCV_VERSION_MAJOR            : Major version part of OpenCV_VERSION: "4"
#      - OpenCV_VERSION_MINOR            : Minor version part of OpenCV_VERSION: "5"
#      - OpenCV_VERSION_PATCH            : Patch version part of OpenCV_VERSION: "0"
#      - OpenCV_VERSION_STATUS           : Development status of this build: ""
#
# ===================================================================================
```

I've followed it and it work like a charm. Basically, you just need to declare the OpenCV modules that you use in the project inside **find_package()**. For example:

```cmake
find_package(OpenCV REQUIRED core videoio)
target_link_libraries(MY_TARGET_NAME ${OpenCV_LIBS})
```

For a complete module's name, you can find in [here](https://docs.opencv.org/4.5.1/)

**Comment by EmmanuelMess** [comment]
@kim-ninh What does that do? How much space is saved from those changes?

**Comment by EmmanuelMess** [comment]
Fixed?
